broj1 = input("Unesite prvi broj:")
broj2 = input("Unesite drugi broj:")
broj3 = input("Unesite treći broj:")
broj4 = input("Unesite četvrti broj:")
broj5 = input("Unesite peti broj:")
broj6 = input("Unesite šesti broj:")

print("ulaz", broj1, broj2,broj3 , broj4 , broj5, broj6)
print("izlaz")
print(broj2)
print(broj4)
print(broj6)
